name: CI

on:
  push:
    branches:
      - master
      - main
      - next
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - master
      - main

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5

      - name: Test
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref != 'master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Change String Case
        id: string
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.repository_owner }}

      - name: branch-names
        id: names
        uses: tj-actions/branch-names@v4.3
        with:
          strip_tag_prefix: v

      - name: Initialization
        id: vars
        run: |
          DOCKER_TAG=${{ steps.names.outputs.current_branch }}
          if [[ "${{ steps.names.outputs.current_branch }}" == "main" ]]; then DOCKER_TAG=latest ; fi
          if [[ "${{ steps.names.outputs.is_tag }}" == "true" ]]; then DOCKER_TAG=${{ steps.names.outputs.tag }} ; fi
          echo ::set-output name=DOCKER_TAG::${DOCKER_TAG}

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.3.0

      - name: Docker Login
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.5.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.string.outputs.lowercase }}/bull-board:${{ steps.vars.outputs.DOCKER_TAG }}
