name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: Release by tag

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: ncipollo/release-action@v1.8.6
        with:
          tag: ${{ github.event.inputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
